config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'help' => 'static_pages#help'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns full title on pages w/o a title
    def full_title(page_title = '')
        base_title = "Rwitter by Myo"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Rwitter app by Myo T Kyaw
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "My Site", "http://myokyaw.com", target:"_blank" %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Rwitter", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Log In", "#" %></li>
        </ul>
      </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render('layouts/shim') %>
</head>
<body>
  <%= render('layouts/header') %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render('layouts/footer') %>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Me</h1>
<p>My name is Myo Thant Kyaw. I'm an aspiring software engineer, currently primarily writing codes in Ruby on its awesome framework Rails!</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Questions, concerns and feedback about the app?</p>
<p>Please <%= link_to "email", "mailto:myotkyaw@gmail.com" %>.</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>We will be providing support feature in the future releases.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Rwitter</h1>
    <p>Welcome to the homepage of my Rwitter app!</p>
    <%= link_to "Sign Up", "#", :class => "btn btn-lg btn-success" %>
</div>
<br />
<%= link_to image_tag("myo.jpg", alt: "Myo Thant Kyaw", style: "width:200px; border-radius:50%;", 
class: "center-block"), "http://myokyaw.com", target: "_blank" %>
    